# Configuration file for a GitHub repository
# See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-repository-metadata for more information

name: "My Repository"
description: "This is a sample repository"

# Issue Templates
issue_templates:
  - name: "Translation Request"
    description: "Request a translation of our project into another language"
    filename: "translation_request.yml"
