name: Translation Request
about: Request a translation of our project into another language

inputs:
  language:
    description: "Please select the language you would like the project to be translated into:"
    type: "string"
    required: true
    options:
      - "Spanish"
      - "French"
      - "German"
      - "Italian"
      - "Other"

  file_link:
    description: "If you have a file that needs to be translated, please provide a link to the file in this repository:"
    type: "string"
    required: false

  additional_info:
    description: "If you have any additional information or special requests for the translation, please describe them here:"
    type: "string"
    required: false

outputs:
  issue_title: "Translation Request - {{ inputs.language }}"
  issue_body: |
    ## Translation Request

    Please fill out the following information to request a translation of our project into another language.

    ### Language

    {{ inputs.language }}

    {% if inputs.file_link %}
    ### File Link

    {{ inputs.file_link }}
    {% endif %}

    {% if inputs.additional_info %}
    ### Additional Information

    {{ inputs.additional_info }}
    {% endif %}
