name: Translation Request
description: Request a translation of our project into another language

title: "Translation Request - {{ inputs.language }}"
body:
  - type: markdown
    attributes:
      value: |
        ## Translation Request

        Please fill out the following information to request a translation of our project into another language.

  - type: input
    id: language
    attributes:
      label: Language
      description: "Please select the language you would like the project to be translated into:"
      required: true

  - type: input
    id: file_link
    attributes:
      label: File Link (Optional)
      description: "If you have a file that needs to be translated, please provide a link to the file in this repository:"
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information (Optional)
      description: "If you have any additional information or special requests for the translation, please describe them here:"
      required: false
      placeholder: "Type your additional information here..."

submit: Submit
